name: "UniFi Protect Backup"
description: "This addon runs the UniFi Protect Backup script in HASS."
version: "0.1.1"
slug: "unifi-protect-backup"
init: false
arch: ["armhf", "armv7", "aarch64", "amd64", "i386"]
options:
  ip_address: ""
  username: ""
  password: ""
  rclone_destination: ""
  rclone_configuration: ""
  verify_ssl: false
  extra_args: ""
schema:
  ip_address: str
  username: str
  password: str
  rclone_destination: str
  rclone_configuration: str
  verify_ssl: bool
  extra_args: str?
