name: "UniFi Protect Backup"
description: "This addon runs the UniFi Protect Backup script in HASS."
version: "0.1.0"
slug: "unifi-protect-backup"
init: false
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.2.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.2.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.2.0
options:
  ip_address: ""
  username: ""
  password: ""
  rclone_destination: ""
  verify_ssl: false
  extra_args: ""
schema:
  ip_address: str
  username: str
  password: str
  rclone_destination: str
  verify_ssl: bool
  extra_args: str?
